<a href="https://colab.research.google.com/github/ToonToonToon/229352-Statical-Learning-For-DataScience-2/blob/main/Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [55]:
import numpy as np

import torch

# Tensor basics

In [5]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


## Basic tensor creation

### Creating a scalar (1D) tensor

In [6]:
scalar = torch.tensor(7)
print(f"Scalar: {scalar}")
print(f"Dimensions: {scalar.ndim}")

vector = torch.tensor([7, 8, 9])
print(f"Vector: {vector}")
print(f"Dimensions: {vector.ndim}")

Scalar: 7
Dimensions: 0
Vector: tensor([7, 8, 9])
Dimensions: 1


### Convert a tensor to scalar

In [7]:
single_element_tensor = torch.tensor([42])

python_number = single_element_tensor.item()

print(f"PyTorch Tensor: {single_element_tensor}")
print(f"Python Number: {python_number}")
print(f"Type: {type(python_number)}")

PyTorch Tensor: tensor([42])
Python Number: 42
Type: <class 'int'>


### Creating 2D tensor

In [2]:
A = torch.tensor([[1, 2], [5, 6]])
A

tensor([[1, 2],
        [5, 6]])

## Tensor and Numpy

### Convert from tensor to numpy array

In [3]:
B = A.numpy()
B

array([[1, 2],
       [5, 6]])

### Convert from numpy array to tensor

In [4]:
C = torch.from_numpy(B)
C

tensor([[1, 2],
        [5, 6]])

## PyTorch and GPU

check if GPU is available

In [8]:
torch.cuda.is_available()

True

In [9]:
C.device

device(type='cpu')

In [10]:
D = C.cuda()
D

tensor([[1, 2],
        [5, 6]], device='cuda:0')

In [11]:
D.device

device(type='cuda', index=0)

In [12]:
C + D

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [15]:
E = D.cpu().numpy()
E

array([[1, 2],
       [5, 6]])

## Basic operations

In [16]:
E * 2

array([[ 2,  4],
       [10, 12]])

In [17]:
E - 2

array([[-1,  0],
       [ 3,  4]])

In [18]:
E * np.array([1,2])

array([[ 1,  4],
       [ 5, 12]])

In [20]:
D.cpu() * np.array([1,2])

/tmp/ipython-input-1707415638.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  D.cpu() * np.array([1,2])


tensor([[ 1,  4],
        [ 5, 12]])

In [21]:
D - 2

tensor([[-1,  0],
        [ 3,  4]], device='cuda:0')

### Matrix multiplication

In [22]:
A = torch.tensor([[4, 5], [8, 9]])
B = torch.tensor([[1, 4], [7, 8]])

torch.matmul(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [23]:
torch.mm(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [24]:
A @ B

tensor([[ 39,  56],
        [ 71, 104]])

## Matrix tranpose

In [26]:
A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [27]:
a = torch.zeros(1, 2, 3)
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [28]:
b = torch.ones(1, 2, 3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [29]:
I = torch.eye(3)
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [30]:
R1 = torch.rand(2, 3)
R1

tensor([[0.8482, 0.2008, 0.6952],
        [0.5536, 0.3818, 0.1881]])

In [31]:
R2 = torch.randn(2, 3)
R2

tensor([[-0.1548,  0.1568,  0.1080],
        [ 1.5285,  1.4848,  2.0954]])

In [32]:
a = torch.arange(6)
a

tensor([0, 1, 2, 3, 4, 5])

## Tensor's shape

### Checking the shape of a tensor

In [33]:
A.shape

torch.Size([2, 2])

In [34]:
A.size()

torch.Size([2, 2])

### Changing the shape of a tensor

In [35]:
u = torch.arange(6)
u.shape

torch.Size([6])

In [36]:
v = u.reshape(2, 3)
v

tensor([[0, 1, 2],
        [3, 4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [57]:
a = torch.arange(4)
b = torch.arange(4) + 1
c = torch.stack([a, b], axis =0)
c

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [59]:
d = torch.stack([a, b], axis =1)
d

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [ ]:
# concatenate
e = torch.cat([a, b], axis =0)
e

In [ ]:
f = torch.cat([a.reshape(2,2), b.reshape(2,2)], axis =0)
f

### Squeezing a tensor (removing an extra dimension)

In [63]:
A = torch.zeros(1, 2, 3)
B = A.squeeze()
B

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [64]:
B.shape

torch.Size([2, 3])

### Unsqueezing a tensor (adding an extra dimension)

In [65]:
# H.shape = (6, )
C = B.unsqueeze(axis=0)
C

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [66]:
C.shape

torch.Size([1, 2, 3])

## Indexing

In [67]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [75]:
P[0:2,0:2]

tensor([[0, 1],
        [4, 5]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [45]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [68]:
x = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)

In [69]:
ones = torch.ones(200, 1)

In [70]:
X = torch.cat((ones, x), dim=1)

In [71]:
y = X @ b + e

In [72]:
XT = X.T
b_hat = torch.inverse(XT @ X) @ XT @ y

In [73]:
y_hat = X @ b_hat

In [74]:
y_np = y.numpy()
y_hat_np = y_hat.numpy()
mse = np.mean((y_np - y_hat_np)**2)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 0.9090806841850281
